### ISSUE TITLE
请问修改完以后，如何可以让本地的设置和插件可以复制到另外一台机器呢？

### ISSUE THREAD

**Issue by hzh-hzh** [ChandlerVer5/utools-plugins#44]
请问修改完以后，如何可以让本地的设置和插件可以复制到另外一台机器呢？

**Comment by ChandlerVer5** [comment]
1. 你可以尝试把该目录复制过去（原本的目录先重命名下）；
  mac上 uTools 插件，配置地址`/Users/bing/Library/Application Support/uTools/`；windows 上，可以自行查找 uTools ;
2. 可以自己做个插件，同步所有配置和插件;

我都没试过，不过第二个理论可行，现在用 windows 少。
